import { Orbitron, Geist_Mono, VT323 } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
});

const vt323 = VT323({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-vt323",
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${orbitron.variable} ${vt323.variable} font-sans antialiased dark`}
      >
        {/* <Navbar /> */}
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
